### ISSUE TITLE
[day08, day10] 中 Server::deleteConnection 疑问

### ISSUE THREAD

**Issue by Young-Flash** [yuesong-feng/30dayMakeCppServer#11]
https://github.com/yuesong-feng/30dayMakeCppServer/blob/d1505975079a5ca7b4186d550bcf6d39435350b5/code/day08/src/Server.cpp#L26-L30
删除连接这里是不是少了 close(sockfd) ？

**Comment by yuesong-feng** [comment]
没有，建议先补一下前面的基础，弄清楚生命周期。socket只对Socket可见，delete conn会触发Connection析构，Connection析构会触发Socket析构，Socket析构关闭socket，涉及到类的管理资源和生命周期问题，这样设计才是最合理的关系。Server类只管理Connection的生命周期，Connection里的Socket都不可见，何况更底层的socket。
