### ISSUE TITLE
菜鸟询问一个调试问题

### ISSUE THREAD

**Issue by nagesbquzhegemingzi** [yuesong-feng/30dayMakeCppServer#14]
Channel *servChannel = new Channel(loop, serv_sock->getFd());
    std::function<void()> cb = std::bind(&Server::newConnection, this, serv_sock);
    servChannel->setCallback(cb);
    servChannel->enableReading();

带佬,你好,在day06的代码里.设置channel的回调为Server::newConnection后,

我在newConnection设置断点后,怎么hit这个断点呢?调试器在
`  for(auto it = chs.begin(); it != chs.end(); ++it){
            (*it)->handleEvent();
        }`
这里单步调试会跑到库函数里,请问有什么办法可以调试newConnection里的代码吗?

**Comment by Young-Flash** [comment]
这个要看你用的 IDE 了，如果是 CLion 的话调试的时候按 F8 可以单步执行当前语句，VSCode 下也有对应的调试方式

**Comment by yuesong-feng** [comment]
在Server的newConnection函数里打断点就行了

**Comment by nagesbquzhegemingzi** [comment]
> Reference in new



> 在Server的newConnection函数里打断点就行了
感谢解答
