### ISSUE TITLE
day5中返回Channel指针的poll函数一些不明白的地方

### ISSUE THREAD

**Issue by RudyPeng** [yuesong-feng/30dayMakeCppServer#19]
https://github.com/yuesong-feng/30dayMakeCppServer/blob/f1e31070e84492514eb101ef57971749d0d37329/code/day05/Epoll.cpp#L44-L50

作者你好，请问下有关于day5中的这两句代码的意思，我在自己电脑上进行了类似的测试，有些地方搞不明白
比如说此时返回的fd = 3，我电脑上虚拟机上运行的ptr的值为0x3，47行令一个Channel *ch = ptr 就是让ch指向0x3这个地址，接着第48行对ch指向的revents进行赋值。我的理解是在0x3作为起始地址的基础上，将revents相应位置0x13进行赋值。但是这样不会产生段错误吗？这样赋值是为了在union的内存后面再腾出4B来存放revents吗？（纠结在这里，还没有看server的代码）
求解答~谢谢

**Comment by yuesong-feng** [comment]
比如说此时返回的fd = 3，我电脑上虚拟机上运行的ptr的值为0x3，~~47行令一个Channel *ch = ptr 就是让ch指向0x3这个地址~~(❌)，~~接着第48行对ch指向的revents进行赋值~~(❌)。我的理解是在0x3作为起始地址的基础上，~~将revents相应位置0x13进行赋值~~(❌)。但是这样不会产生段错误吗？ **_(不会)_** 这样赋值是为了在union的内存后面再腾出4B来存放revents吗？ **_(不是)_** 

可以先学一下C/C++语言，以及计算机组成原理，可以参考《深入理解计算机系统（第三版）》。

**Comment by RudyPeng** [comment]
不好意思，漏看了updataChannel中的代码，吸取教训了
