### ISSUE TITLE
day10中，为何ThreadPool给EventLoop持有，而不是放到Server中？

### ISSUE THREAD

**Issue by aqianchu** [yuesong-feng/30dayMakeCppServer#2]
day10中，为何ThreadPool给EventLoop持有，而不是放到Server中？

**Comment by yuesong-feng** [comment]
day10采用one thread per task模式，线程池放在EventLoop是因为Channel类有EventLoop对象成员，使用方便，放在Server则需要注册回调函数。day12将采用one thread per loop，此时线程池会在Server中，一个线程是一个sub-EventLoop。
