### ISSUE TITLE
似乎有个错漏处

### ISSUE THREAD

**Issue by jon2180** [yuesong-feng/30dayMakeCppServer#3]
https://github.com/yuesong-feng/30dayMakeCppServer/blob/8af5aab2be44b9f9013ec28f6d4cb3c62f859fca/code/day04/Socket.cpp#L17

似乎有个错漏

**Comment by yuesong-feng** [comment]
多谢，应该是!=，你可以提交一个PR修复

**Comment by jon2180** [comment]
你好，我仿照你的教程写了自己的版本，修复了这个问题（ == 改成了 != ）。但似乎存在另外一个问题。看这个析构函数，这个 socket 是应该及时回收的。

然后我查阅了下面这一段代码

https://github.com/yuesong-feng/30dayMakeCppServer/blob/aa16da2540db20549187d05629cd3b1eee1fc900/code/day06/src/Server.cpp#L54-L60

根据我的理解，这段代码没有回收 socket 的空间，却也没有维护 socket 指针，似乎必然存在内存泄露。 我尝试在自己的版本中使用了智能指针。

```c++
// excerpt
auto clientSocket = std::make_shared<Socket>(serverSock->Accept( /* omit */ ));
```

程序在处理事件时，正确地释放了 `clientSocket` 的内存，但相应地造成自动关闭了客户端连接，移除了epoll 对  `serverSock->Accept()` 返回的 socket 连接的监听。

> 我自己的临时解决方案是在类中设置了一个属性 `bool autoRelease_`  来控制是否自动关闭连接。

我有些疑惑，这些 socket 对象是作为临时对象存在吗，还是需要维护起来的对象呢？

**Comment by yuesong-feng** [comment]
所有客户端Socket都不是临时对象，需要由Connection类维护、管理生命周期，在day08的教程里会处理。另外day13后的版本不会有任何内存泄漏问题，前面的代码重点放在架构上，忽略了一些细节。
