### ISSUE TITLE
代码存在内存泄露的问题

### ISSUE THREAD

**Issue by heheda123123** [yuesong-feng/30dayMakeCppServer#35]
raii是c++最重要的资源管理方案咋不用呢，里面全是裸指针。
从第四课封装类开始，到后面第15课都存在内存泄露的问题。最明显的就是new的InetAddress和Socket到关闭了客户端连接还没有释放。

**Comment by yuesong-feng** [comment]
1. 工业上一些大型项目明确规定禁止使用C++智能指针，如OceanBase、openGauss等。
2. 初学不建议用智能指针，手动实现raii可以帮助理解各对象的生命周期。
3. 本项目源码中已经实现了raii，没有内存泄漏，理解错误。如Socket在生命周期结束后会释放。

**Comment by heheda123123** [comment]
我也没说要用智能指针呀。。。
而且你这对raii理解有误会吧，对象应该封装资源，当对象生命周期结束的时候也就不再需要资源了，自然地在析构函数释放资源才对。不在析构函数释放资源遇到异常就资源泄露了。

另外就算不会产生异常，你这个代码也有内存泄露，
1 你看day15 Acceptor.cpp 39行，这里new Socket，
2 然后调用了设置的回调函数 Server::NewConnection()，在这里面一是用上面的Socket对象地址构造了一个Connection对象，二是对Connetion对象设置了回调执行 Server::DeleteConnection
3 在Connection的构造函数里面，把Socket对象地址用来构造了一个Channel对象，Channel对象倒是在Connection析构的时候删除了，但是就没管Socket对象了，在Channel析构的时候最终也只是在 Poller.cpp的第82行把监听的fd从epoll中删除了，也没看到delete 前面new的 Socket对象
4 再看第2步还设置了个回调执行 Server::DeleteConnection，执行的代码在Server.cpp 56行，这个函数也只是删除 Connection 对象，都没提Socket对象
5 这样的话，每来一个客户端都会泄露一个Socket对象，断开的时候也没释放他

**Comment by yuesong-feng** [comment]
Socket资源属于Connection类，客户端断开连接的时候，会造成Connection生命周期终止，Connection在析构的时候，会将Socket析构，Connection.cpp第40行。

**Comment by heheda123123** [comment]
我看错了，确实释放了Socket对象，不好意思

**Comment by yuesong-feng** [comment]
我搞错了，这确实不是raii，后续的教程考虑用raii重写。

**Comment by yuesong-feng** [comment]
我搞错了，这确实不是raii，后续的教程考虑用raii重写。

**Comment by yuesong-feng** [comment]
我搞错了，这确实不是raii，后续的教程考虑加上raii来管理资源。

**Comment by heheda123123** [comment]
嗯嗯。因为我认为的raii最重要的一点是得在析构函数中释放资源，让对象的生命周期和资源持有周期一致。否则不能保证在产生异常的情况下资源正常释放。前面看仓库里的代码，各种位置都有释放就晕了。不过在没有异常的情况下，现在的代码确实都释放了。

**Comment by yuesong-feng** [comment]
day15之前这样写，或许可以让初学者更好地理解对象的生命周期，大项目肯定不适用，有异常就很容易内存泄漏。
因为出于学习目的，我认为手动管理资源也是Cpper必备的技能。
一开始就用智能指针的话，虽然简单方便，初学者也不容易搞明白，不知道对象在哪儿分配资源、在哪儿释放。
后续会把裸指针换成智能指针，或者自己封装raii类。
