### ISSUE TITLE
有没有可能未来增加 GUI的支持?

### ISSUE THREAD

**Issue by YukunJ** [yuesong-feng/30dayMakeCppServer#41]
首先非常感谢楼主的更新. So far very solid.

想问问之后可不可能在Client端增加GUI的支持, 比如QT

---

同时想请问这个Repo的进度是和你另一个库`Pine` 一致的吗? 即这里的Day Max即是现在`Pine`的Head?

**Comment by yuesong-feng** [comment]
GUI不熟悉、暂时不考虑。
pine有比最近day更加新的代码。
