### ISSUE TITLE
day02的小小问题

### ISSUE THREAD

**Issue by Anu-orange** [yuesong-feng/30dayMakeCppServer#57]
在客户端进行ctrl+c之后，在服务端显示了两条信息，一条是读取字节数等于0的情况，一条则是读取字节数为-1的情况，有哪位大佬知道嘛
![image](https://github.com/yuesong-feng/30dayMakeCppServer/assets/86885288/9cea89bc-bd11-44f7-a9f3-c83300b6880c)

**Comment by hnkjdaxzzq** [comment]
我没出现你这种情况呀，你可以仔细看看你的代码是不是和作者的代码是一样的
![image](https://github.com/yuesong-feng/30dayMakeCppServer/assets/54497949/4b97d9fb-b384-47ae-a79d-d8d3fb3c22cf)

**Comment by Anu-orange** [comment]
> 我没出现你这种情况呀，你可以仔细看看你的代码是不是和作者的代码是一样的 ![image](https://user-images.githubusercontent.com/54497949/253711401-4b97d9fb-b384-47ae-a79d-d8d3fb3c22cf.png)

好的，谢谢，我再瞅瞅啥原因
